name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'release**'
    tags:
      - 'v**'

jobs:
  build:
    name: Build windows binaries
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run build
        env:
          CI: true
          PKG_CACHE_PATH: ${{ runner.temp }}
        run: |
          corepack enable
          # try and avoid timeout errors
          yarn config set httpTimeout 100000

          yarn install
          yarn do:build-win32:ci

      - name: Verify build
        run: yarn verify:build-win32
        env:
          CI: true

      - name: ZIP output
        env:
          CI: true
          PKG_CACHE_PATH: ${{ runner.temp }}
        run: |
          yarn zip-deploy -win-x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: deploy

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows
          path: deploy

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: deploy/*.zip
          prerelease: ${{ contains(github.ref, '-') }}
          fail_on_unmatched_files: true
